export const iGenres = [
  { Action: "material-symbols-light--swords" },
  { Animation: "mdi--teddy-bear" },
  { Adventure: "material-symbols-light--forest-rounded" },
  { Comedy: "material-symbols-light--theater-comedy-rounded" },
  { Crime: "fa--user-secret" },
  { Documentary: "solar--document-bold" },
  { Drama: "ph--mask-sad-fill" },
  { Family: "mdi--family" },
  { Fantasy: "game-icons--sea-dragon" },
  { History: "simple-icons--dreamstime" },
  { Horror: "ri--ghost-smile-fill" },
  { Music: "solar--music-notes-broken" },
  { Mystery: "game-icons--secret-book" },
  { Romance: "ph--heart-fill" },
  { "Science Fiction": "material-symbols-light--stylus-laser-pointer" },
  { Thriller: "game-icons--ghost-ally" },
  { "TV Movie": "material-symbols-light--tv-outline" },
  { War: "mdi--tank" },
  { Western: "fa-solid--hat-cowboy" },
];
